baseurl = "https://thehar.com"
languageCode = "en"
title = "Harley Alaniz | DevOps Architect"
theme = "hucore"
copyright = "&copy; 2017 | Follow on <a href=\"https://twitter.com/thehar\" target=\"_blank\">Twitter</a> | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"
disqusShortname = "thehar"
googleAnalytics = "UA-396130-18"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Openly gay DevOps engineer, based in San Francisco"
keywords = ["workhack", "git", "notes", "innerthoughts", "tools"]
author = "Harley Alaniz"
sharingicons = true
displayauthor = true

[params.highlight]
style = "github"
languages = ["go", "ruby", "python", "bash", "dockerfile"]

[[params.social]]
url = "https://github.com/thehar"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/thehar"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://linkedin.com/in/thehar"
fa_icon = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

[[params.socialshare]]
url = "https://linkedin.com/in/thehar"
fa_icon = "fa-linkedin-square"
